### ISSUE TITLE
Consider supporting more KCL config options

### ISSUE THREAD

**Issue by ewestern** [500px/kinesis-stream#4]
For example, I need to use a custom RetrievalConfig in certain cases, but that can't be done with the mainline ConsumerConfig API.

**Comment by ukayani** [comment]
@ewestern 

That is true, the ConsumerConfig only supports common configuration options at the moment. The issue with enumerating all the config options in ConsumerConfig is it becomes more difficult to maintain as AWS makes changes. Do you have any suggested way of supporting different config options via the ConsumerConfig? Some sort of API pattern you would find useful?

**Comment by ewestern** [comment]
Sorry for the delay, @ukayani 
I guess one option would be just to leave your simplified ConsumerConfig as-is, but then provide a separate factory method that creates a Source and takes only a KinesisClientLibConfiguration as argument. That way, you wouldn't have to worry about changes on the aws side (at least within a given major version).

**Comment by mmccuiston** [comment]
+1 on supporting an override of the RetreivalConfig

I took a shot at adding this in the pull request below.
https://github.com/500px/kinesis-stream/pull/6

**Comment by nbenns** [comment]
0.1.7 released on maven central containing the code changes.
