### ISSUE TITLE
Build.sbt ArtifactID incorrect

### ISSUE THREAD

**Issue by RommelTJ** [500px/kinesis-stream#8]
In the [Readme file](https://github.com/500px/kinesis-stream/blob/master/README.md), the build instructions show the following: 
`libraryDependencies += "com.500px" %% "kinesis-stream" % "0.1.6"`

However, that artifact ID is not present in most common repositories and when attempting to build you will get: 
`sbt.librarymanagement.ResolveException: unresolved dependency: com.500px#kinesis-stream;0.1.6: not found`

Searching on Sonatype it looks like it should be: 
`libraryDependencies += "com.500px" %% "kinesis-stream_2.12" % "0.1.7"`

**Comment by nbenns** [comment]
fixing in #10
